name: Tests

on:
  repository_dispatch:
  pull_request:
    branches:
    - 'main'

permissions:
  contents: write
  checks: write

jobs:
  check_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Clone Epitech Coding style
        run: git clone https://github.com/Epitech/coding-style-checker.git
      - name: Access cloned repository content
        run: |
          chmod +x ./coding-style-checker/coding-style.sh
          ./coding-style-checker/coding-style.sh ./server .
          cat coding-style-reports.log
      - name: Verify coding style
        run: |
            error=false
            while IFS= read -r line; do
                if [[ $line =~ (MAJOR|MINOR|INFO) ]]; then
                        IFS=': '
                        read -r -a array <<< "$line"
                        echo "::error title=Coding style error:: file:${array[0]}, line:${array[1]}, coding-style:${array[2]}-${array[3]}"
                        error=true
                fi
                done < coding-style-reports.log
            if [ $error = true ]
            then
                exit 1
            else
                exit 0
            fi
  check_compilation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.1'
          enable-stack: true
      - name: Compile
        run: make
        timeout-minutes: 5
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@v2
        with:
          files: "glados"
          fail: true
  run_tests:
    needs: check_compilation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: '9.8.1'
          enable-stack: true
      - name: Run tests
        run: make tests_run
        timeout-minutes: 5


